### ISSUE TITLE
22 May 2015 - Viber update ruined the indicator

### ISSUE THREAD

**Issue by dimitriscsd** [karas84/viberwrapper-indicator#8] opened 2015-05-22 17:34 UTC
Hello.

There was a viber update today and unfortunately after update and a restart, the annoying icon is on the top left again...

They must have changed something and rendered the wrapper useless.

Would you be so kind as to take a look into this? I would greatly appreciate it.

Thanks in advance.

**Comment by cdysthe** [comment] 2015-05-22 18:43
Here too. That little icon is in the way always covering either the close button or something else. Please fix.

**Comment by karas84** [comment] 2015-05-22 21:46
That's strange, I can't seem to find any update. Anyway I updated the code, give it a go and see if it works now.

**Comment by cdysthe** [comment] 2015-05-22 23:46
I'm not sure how to run it from Github so I guess I'll have to wait until it's updated in the WebUpd8 PPA. I think the problem is caused by an update in Ubuntu, not in Viber since haven't updated Viber in ages.

**Comment by psybaron** [comment] 2015-05-23 07:38
Same here. Update to "viberwrapper-indicator" package this morning broke it icon. Will wait for WebUpd8 PPA to get fixed to this repo.

**Comment by dburba** [comment] 2015-05-23 08:55
The same for me - viber icon on top left corner is back.

**Comment by cengizonkal** [comment] 2015-05-23 09:01
The same for me - viber icon on top left corner is back.

**Comment by hrhthegreat** [comment] 2015-05-23 10:47
I couldn't find any update for Viber. Just i installed updated viberindicator from ppa and icon is back on top left. Is there any new update for viber? Why did you update the indicator so?

**Comment by anywhim** [comment] 2015-05-23 19:01
Hi! I had the same problem as another users. I updated /usr/bin/viberwrapper-indicator to version in the repository and run Viber indicator in dash (not Viber). Now I have icon in the right place.

**Comment by dburba** [comment] 2015-05-23 19:14
Thanks, anywhim. It works.

**Comment by Paulines38** [comment] 2015-05-24 19:27
Hi guys,

I got the same issue. I checked the code on /usr/bin on my pc and the one on github. From what I could see the version that I have really looks like the one that was commited on Dec 5, 2014. There is only a small difference that is causing the issue.
On line 436:
"if geom['width'] == 22 and geom['height'] == 22:"

was replaced by:
"if geom['width'] == 10 and geom['height'] == 10 or geom['width'] == 22 and geom['height'] == 22:"

I updated the file /usr/bin/viberwrapper-indicator with "if geom['width'] == 22 and geom['height'] == 22:" and it fixed the issue.

**Comment by cdysthe** [comment] 2015-05-25 01:56
@Paulines38 Thanks! That took care of it! Works perfectly now.

**Comment by karas84** [comment] 2015-05-25 06:54
Glad it worked. I'm closing the issue then.

**Closed by karas84** 2015-05-25 06:54 UTC

**Comment by dimitriscsd** [comment] 2015-05-25 09:06
I confirm that it works. The icon on the left flashes for a second but I suppose that's ok.

Thanks for everything guys. I really hope viber will fix issues like these themselves so we don't have to rely on workarounds...

**Comment by cdysthe** [comment] 2015-05-25 15:04
@dimitriscsd Honestly I do not think they will. It's only in Ubuntu you get the floating icon. In other DE's it's in the system tray. I also know people who like it that being able to move the notification icon around. But let's hope! :)
